#!/bin/sh

# Link in the environment ini.
ini=${APP_ENVIRONMENT}.ini;
env_d=/etc/php5/custom.conf.d;
if [ -f "$env_d/$ini" ]; then
    for d in $(find /etc/php5 -type d -name "conf.d"); do
        if [ -f "$d/999_$ini" ]; then
            continue;
        fi

        (cd $d && ln -s $env_d/$ini 999_$ini;);
    done;
fi

# Call whatever was passed to us.
$@
